# ============================================
# WALLUST THEME (Converted from Matugen)
# ============================================

[theme]
name=Wallust Pop
author=Kushagra

# Core colors
accent=#4C73A0
text=#B2CFFF
textDim=#A3C0F0
textMuted=#6480AC

# General Colors
logo=#6480AC
header=#6480AC
footer=#6480AC
help=#5176A1
link=#467DBD
nowplaying=#4C73A0

# Playlist View
playlist.rownum=#6480AC
playlist.title=#B2CFFF
playlist.playing=#4C73A0

# Track View
trackview.title=#697C9B
trackview.artist=#4C73A0
trackview.album=#5176A1
trackview.year=#A3C0F0
trackview.time=#3F79BC
trackview.lyrics=#B2CFFF
trackview.visualizer=#4C73A0

# Library View
library.artist=#6480AC
library.album=#5176A1
library.track=#5176A1
library.enqueued=#697C9B
library.playing=#4C73A0

# Search
search.label=#6480AC
search.query=#4C73A0
search.result=#B2CFFF
search.enqueued=#697C9B
search.playing=#4C73A0

# Progress
progress.filled=#4C73A0
progress.empty=#6480AC
progress.elapsed=#4C73A0

# Status
status.info=#B2CFFF
status.warning=#444F61
status.error=#444F61
status.success=#45556D
