default_color_bg=
default_color_fg=0xB2CFFF
dialog_attr=
dialog_attr_selected=reverse
dialog_color_bg=
dialog_color_fg=0xB2CFFF
entry_attr=
entry_color_bg=
entry_color_fg=
help_attr=
help_color_bg=0x05050C
help_color_fg=0xB2CFFF
history_name_attr=bold
history_name_attr_selected=reverse
history_name_recv_color_bg=
history_name_recv_color_fg=0x4C73A0
history_name_sent_color_bg=
history_name_sent_color_fg=0x697C9B
history_text_attachment_color_bg=
history_text_attachment_color_fg=0xA3C0F0
history_text_attr=
history_text_attr_selected=reverse
history_text_quoted_color_bg=
history_text_quoted_color_fg=0x6480AC
list_color_fg=0xB2CFFF
list_color_unread_fg=0x4C73A0
listborder_color_fg=0x6480AC
status_color_bg=0x6480AC
status_color_fg=0x4C73A0
top_color_bg=0x6480AC
top_color_fg=0xB2CFFF
