# Wallust Hyprland colors - Fixed Filter Syntax
$image = /home/kushagra/dotfiles/assets/Wallpaper/050.png

$background = rgba(060300ff)
$foreground = rgba(EFC4E7ff)

$color0 = rgba(090501ff)
$color1 = rgba(585C64ff)
$color2 = rgba(595F68ff)
$color3 = rgba(6A798Dff)
$color4 = rgba(A16D5Dff)
$color5 = rgba(637996ff)
$color6 = rgba(8F7289ff)
$color7 = rgba(E1B7D9ff)
$color8 = rgba(9A7594ff)
$color9 = rgba(626773ff)
$color10 = rgba(646B78ff)
$color11 = rgba(647B9Bff)
$color12 = rgba(D08770ff)
$color13 = rgba(6184B0ff)
$color14 = rgba(B68FAFff)
$color15 = rgba(E7D3E3ff)
