#######################################
# ENVIRONMENT
#######################################
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = HYPRLAND_NO_DMABUF,1
env = QT_QPA_PLATFORMTHEME,gtk3
env = WLR_NO_HARDWARE_CURSORS,1

source = ~/.config/hypr/hypr-colors.conf

#######################################
# KEYBINDS SOURCE
#######################################
source = ~/.config/hypr/hyprland/keybinds.conf

#######################################
# AUTOSTART
#######################################
exec-once = sleep 1 && swww-daemon &
exec-once = udiskie --no-tray
#exec-once = ~/.config/hypr/scripts/wallpaper-cycle.sh &
exec-once = kitty
#exec-once = hyprpanel &
exec-once = qs -c ii &
exec-once = mpd-mpris
exec-once = wl-paste --watch cliphist store
#exec-once = waybar
exec-once = (setsid jams > /dev/null 2>&1 &)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets
exec-once = udiskie --no-tray
exec-once = /home/kushagra/music/scripts/mpd_listener.sh &
exec-once = python ~/.config/wallust/scripts/server.py > /dev/null 2>&1 &

#######################################
# DISPLAY
#######################################
monitor = , preferred, auto, 1.33

#######################################
# INPUT
#######################################
input {
    kb_layout = us
    natural_scroll = true

    touchpad {
        natural_scroll = true
    }
}

#######################################
# GESTURES
#######################################
gestures {
    workspace_swipe_distance = 150
    workspace_swipe_cancel_ratio = 0.2
    workspace_swipe_min_speed_to_force = 20
    workspace_swipe_direction_lock = false
    gesture = 3, horizontal, workspace, scale: 0.5
}

#######################################
# ANIMATIONS
#######################################
source = ~/.config/hypr/source/animations/active/active.conf

#######################################
# LAYOUT
#######################################
general {
    layout = dwindle
    gaps_in = 5
    gaps_out = 10
    resize_on_border = true
}

#######################################
# DECORATION
#######################################
decoration {
    active_opacity = 0.85
    inactive_opacity = 0.85
    fullscreen_opacity = 0.85
    rounding = 10

    blur {
        enabled = true
        size = 10
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
        noise = 0.05
        contrast = 0.9
        brightness = 0.9
    }

    shadow {
        enabled = true
        range = 20
        render_power = 2
        color = rgba(0, 0, 0, 0.20)
        color_inactive = rgba(0, 0, 0, 0.10)
    }
}

#######################################
# LAYER RULES
#######################################
layerrule = blur, rofi
layerrule = blur, ^(org.btrfs_assistant.BtrfsAssistant)
#layerrule = ignorezero, rofi
#layerrule = ignorealpha, rofi
layerrule = blur, hyprpanel
layerrule = ignorealpha, hyprpanel

#######################################
# WINDOW RULES
#######################################
windowrulev2 = opacity 0.4 0.4, class:^(zathura)$
windowrulev2 = opacity 1.0 override, class:zen, title:^(.*YouTube.*)$
windowrulev2 = opacity 0.85, class:thunar
windowrulev2 = dimaround 0.1, class:thunar
windowrulev2 = opacity 0.85 override, class:org.musicbrainz.Picard
windowrulev2 = opacity 1.0 override, class:mpv
windowrulev2 = opacity 0.85 0.75, class:^(org.btrfs_assistant.BtrfsAssistant)$
