-- Auto-generated by Matugen
return {
  "nvim-lualine/lualine.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },

  config = function()
    local lualine = require("lualine")
    local lazy_status = require("lazy.status")

    -- Matugen-generated color table
    local C = {
      bg        = "#0f1512",
      bg_dark   = "#3f4945",
      bg_light  = "#dbe5df",
      fg        = "#dee4e0",
      fg_dim    = "#bfc9c4",
      primary   = "#87d6bd",
      secondary = "#b2ccc2",
      tertiary  = "#a9cbe2",
      error     = "#ffb4ab",
    }

    local my_lualine_theme = {
      normal = {
        a = { bg = C.primary, fg = C.bg, gui = "bold" },
        b = { bg = C.bg_dark, fg = C.fg },
        c = { bg = C.bg, fg = C.fg_dim },
      },
      insert = {
        a = { bg = C.secondary, fg = C.bg, gui = "bold" },
        b = { bg = C.bg_dark, fg = C.fg },
        c = { bg = C.bg, fg = C.fg_dim },
      },
      visual = {
        a = { bg = C.tertiary, fg = C.bg, gui = "bold" },
        b = { bg = C.bg_dark, fg = C.fg },
        c = { bg = C.bg, fg = C.fg_dim },
      },
      replace = {
        a = { bg = C.fg_dim, fg = C.bg, gui = "bold" },
        b = { bg = C.bg_dark, fg = C.fg },
        c = { bg = C.bg, fg = C.fg_dim },
      },
      command = {
        a = { bg = C.error, fg = C.bg, gui = "bold" },
        b = { bg = C.bg_dark, fg = C.fg },
        c = { bg = C.bg, fg = C.fg_dim },
      },
      inactive = {
        a = { bg = C.bg_dark, fg = C.fg_dim },
        b = { bg = C.bg_dark, fg = C.fg_dim },
        c = { bg = C.bg_dark, fg = C.fg_dim },
      },
    }

    lualine.setup({
      options = {
        theme = my_lualine_theme,
      },
      sections = {
        lualine_x = {
          {
            lazy_status.updates,
            cond = lazy_status.has_updates,
            color = { fg = C.tertiary },
          },
          "encoding",
          "fileformat",
          "filetype",
        },
      },
    })
  end,
}

