# Core Colors
background            #060300
foreground            #EFC4E7
selection_foreground  #EFC4E7
selection_background  #9A7594
cursor                #A16D5D
cursor_text_color     #090501

# Regular Colors
color0  #090501                
color1  #585C64                  
color2  #595F68                
color3  #6A798D               
color4  #A16D5D  
color5  #637996
color6  #8F7289              
color7  #E1B7D9               

# Bright Colors
color8  #9A7594          
color9  #626773                  
color10 #646B78                
color11 #647B9B                
color12 #D08770    
color13 #6184B0  
color14 #B68FAF              
color15 #E7D3E3
